set(_CATKIN_CURRENT_PACKAGE "waypoint_flier")
set(waypoint_flier_VERSION "0.0.1")
set(waypoint_flier_MAINTAINER "Matej Petrlik <matej.petrlik@fel.cvut.cz>")
set(waypoint_flier_PACKAGE_FORMAT "2")
set(waypoint_flier_BUILD_DEPENDS "roscpp" "nodelet" "geometry_msgs" "nav_msgs" "mrs_msgs" "mrs_lib" "dynamic_reconfigure")
set(waypoint_flier_BUILD_EXPORT_DEPENDS "roscpp" "nodelet" "geometry_msgs" "nav_msgs" "mrs_msgs" "mrs_lib" "dynamic_reconfigure")
set(waypoint_flier_BUILDTOOL_DEPENDS "catkin")
set(waypoint_flier_BUILDTOOL_EXPORT_DEPENDS )
set(waypoint_flier_EXEC_DEPENDS "roscpp" "nodelet" "geometry_msgs" "nav_msgs" "mrs_msgs" "mrs_lib" "dynamic_reconfigure")
set(waypoint_flier_RUN_DEPENDS "roscpp" "nodelet" "geometry_msgs" "nav_msgs" "mrs_msgs" "mrs_lib" "dynamic_reconfigure")
set(waypoint_flier_TEST_DEPENDS )
set(waypoint_flier_DOC_DEPENDS )
set(waypoint_flier_URL_WEBSITE "")
set(waypoint_flier_URL_BUGTRACKER "")
set(waypoint_flier_URL_REPOSITORY "")
set(waypoint_flier_DEPRECATED "")